### ISSUE TITLE
What is the meaning of the number in SVG file names?

### ISSUE THREAD

**Issue by daotrungkien** [skishore/makemeahanzi#16]
As the question in the title, what is the meaning of the number in SVG file names? I have no idea on how to map this number to the character code, or the character index in the word-list files.

Thanks!

**Comment by mcfarljw** [comment]
It is the unicode to decimal value. For example 你 would be 20320. You can check it using this tool:

https://r12a.github.io/apps/conversion/

**Comment by skishore** [comment]
That's right. The reason for using the codepoint instead of the unicode character is that some filesystems have trouble with non-ASCII names (for example, Android seems to). If you're using Javascript, you can get the codepoint of the character `x` as `x.charCodeAt(0)`. I updated the README to include that information.
