### ISSUE TITLE
賴瀨懶籟癩 stroke order error

### ISSUE THREAD

**Issue by parsimonhi** [skishore/makemeahanzi#21]
Hello,

The stroke order of the 刀 component in 賴瀨懶籟癩 seems incorrect.

Hope it helps!

**Comment by skishore** [comment]
That's true, the stroke order is incorrect, but the font itself uses the wrong component in that place (it uses 刀 instead of the correct ⺈). That incorrect component explains why the stroke order is wrong, since it differs between those two. I'm not sure what the best fix here is. I haven't been updating the font glyphs themselves, so far.

**Comment by parsimonhi** [comment]
It is not the "wrong" component. 刀 component is a variation often used in the traditional form of the character. See for instance http://www.archchinese.com/chinese_english_dictionary.html?find=%E8%B3%B4 and https://en.wiktionary.org/wiki/%E8%B3%B4 for 賴. So if the displayed shape of the component is "刀", the stroke order must be set accordingly. Some fonts use ⺈ component even for the traditional form. In this case (i.e. if the displayed shape of the component is ⺈) it is correct to keep your current stroke order. But you cannot display a component shape and used the stroke order of the other component.

**Comment by skishore** [comment]
Ah, thanks for the information! I have a lot to learn about traditional characters. I'll try to make those fixes this weekend.
