### ISSUE TITLE
Strokes 4 and 5 in 再 should be swapped.

### ISSUE THREAD

**Issue by yzaretskiy** [skishore/makemeahanzi#51]
Horizontal first, then vertical.

**Comment by skishore** [comment]
I have a strong hunch that you're right - that order feels correct, some native speakers I've talked to agree as well - but Wikipedia and some other pages list the current order for 再. They reference this PRC document for canonical orders: http://www.yys.ac.cn/gfbz/scanning/bsgf/bsgf.htm (see also both links here: https://chinese.stackexchange.com/questions/97/is-there-an-authoritative-reference-for-the-stroke-order-of-simplifed-characters)

Unfortunately, those links are dead. Since the various references are actually ambiguous in this case, I'd like to get confirmation - do you know of any resources that could provide that?

**Comment by skishore** [comment]
Oh! From another issue, someone linked https://upload.wikimedia.org/wikipedia/commons/5/54/%E7%8E%B0%E4%BB%A3%E6%B1%89%E8%AF%AD%E9%80%9A%E7%94%A8%E5%AD%97%E7%AC%94%E9%A1%BA%E8%A7%84%E8%8C%83.pdf - I'll take a look there and figure it out.

**Comment by skishore** [comment]
On page 24 of that document, 再 is given the current stroke order (vertical, then horizontal).

It feels strange, but this is an official reference. If there's a more recent official source with a different answer, I'll reopen the issue.

**Comment by yzaretskiy** [comment]
Just FYI, my sources (much less official) were the Pleco dictionary and the chinesefor.us website. I wonder how they arrived at the alternative stroke order.
